# Final Project

#Kevin Hansen, Peter Henry, Noel Ford

```{r}
# Reading in the CSV file as a data frame
library(tidyverse)
library(readr)
df <- read_csv("C:\\Users\\kchan\\OneDrive\\Desktop\\Police_Department_Incident_Reports__2018_to_Present_20240208.csv")

```

```{r}
#Creating a subset of the original data frame with only relevant data
incidentFrame <- df[c("Incident Date", "Incident Time", "Incident Year", "Incident Day of Week",
                       "Incident ID", "Incident Number", "Report Type Code", "Report Type Description", "Incident Code",
                       "Incident Category", "Incident Subcategory", "Incident Description", "Police District")]

```

```{r}
#Table of the police districts
table(incidentFrame$`Police District`)
#Remove Incidences that were not in SF
incidentFrame2 <- subset(incidentFrame, !(incidentFrame$`Police District` %in% c("Out of SF"))) 
#Confirm Removal of Out of SF
table(incidentFrame2$`Police District`)
```

```{r}
# Remove Incident code, report type/description, ID, subcategory, and description.
incidentFrame2 <- incidentFrame2[,-5:-9]
incidentFrame2 <- incidentFrame2[,-6:-7]
glimpse(incidentFrame2)
# Remove Data from 2024 because incomplete data for the year
incidentFrame2 <- incidentFrame2[incidentFrame2$`Incident Year` < 2024,]
# Table showing the Number of incidences per incident category
table(incidentFrame2$`Incident Category`)
```
```{r}
# Break up data set based on police district
bayviewDF <- incidentFrame2[incidentFrame2$"Police District" == "Bayview",]
centralDF <- incidentFrame2[incidentFrame2$"Police District" == "Central",]
inglesideDF <- incidentFrame2[incidentFrame2$"Police District" == "Ingleside",]
missionDF <- incidentFrame2[incidentFrame2$"Police District" == "Mission",]
northernDF <- incidentFrame2[incidentFrame2$"Police District" == "Northern",]
parkDF <- incidentFrame2[incidentFrame2$"Police District" == "Park",]
RichmondDF <- incidentFrame2[incidentFrame2$"Police District" == "Richmond",]
southernDF <- incidentFrame2[incidentFrame2$"Police District" == "Southern",]
TaravalDF <- incidentFrame2[incidentFrame2$"Police District" == "Taraval",]
tenderloinDF <- incidentFrame2[incidentFrame2$"Police District" == "Tenderloin",]

```

```{r}
#Break up data set based on year
year_2018 <- incidentFrame2[incidentFrame2$"Incident Year" == 2018,]  
year_2019 <- incidentFrame2[incidentFrame2$"Incident Year" == 2019,] 
year_2020 <- incidentFrame2[incidentFrame2$"Incident Year" == 2020,] 
year_2021 <- incidentFrame2[incidentFrame2$"Incident Year" == 2021,] 
year_2022 <- incidentFrame2[incidentFrame2$"Incident Year" == 2022,] 
year_2023 <- incidentFrame2[incidentFrame2$"Incident Year" == 2023,] 
```

```{r}
library(Rcmdr)
#Bar Graph of Number of Incidents per Police District
with(incidentFrame2, Barplot(incidentFrame2$`Police District`, xlab="Police District", ylab="Frequency", label.bars=TRUE))

# Bar Graphs of Incident cases per Police District per category
with(incidentFrame2, Barplot(incidentFrame2$`Incident Category`, by=incidentFrame2$`Police District`, 
  style="divided", legend.pos="above", xlab='Incident Category', 
  ylab="Frequency", label.bars=FALSE))

# Bar Graphs of Incident cases per Police District per category
with(incidentFrame2, Barplot(incidentFrame2$`Police District`, by=incidentFrame2$`Incident Category`, 
  style="divided", legend.pos="above", xlab='Police District', 
  ylab="Frequency", label.bars=FALSE))

```

```{r}
# Central PD Forecast for number of crimes going forward

# Years
dataYears <- c(2018, 2019, 2020, 2021, 2022, 2023)

# Number of Incidents per Year
cpdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Central",]),
                  nrow(year_2019[year_2019$`Police District` == "Central",]),
                  nrow(year_2020[year_2020$`Police District` == "Central",]),
                  nrow(year_2021[year_2021$`Police District` == "Central",]),
                  nrow(year_2022[year_2022$`Police District` == "Central",]),
                  nrow(year_2023[year_2023$`Police District` == "Central",]))
# Create data frame of vectors
cpdDF <- data.frame(dataYears, cpdIncidents)
# Create linear model and extrapolate
ggplot(cpdDF, aes(x=dataYears, y=cpdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Central Police District")

```
```{r}
# Mission PD Forecast for number of crimes going forward

# Number of Incidents per Year
mpdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Mission",]),
                  nrow(year_2019[year_2019$`Police District` == "Mission",]),
                  nrow(year_2020[year_2020$`Police District` == "Mission",]),
                  nrow(year_2021[year_2021$`Police District` == "Mission",]),
                  nrow(year_2022[year_2022$`Police District` == "Mission",]),
                  nrow(year_2023[year_2023$`Police District` == "Mission",]))
# Create data frame of vectors
mpdDF <- data.frame(dataYears, mpdIncidents)
# Create linear model and extrapolate
ggplot(mpdDF, aes(x=dataYears, y=mpdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Mission Police District")
```
```{r}
# Northern PD Forecast for number of crimes going forward

# Number of Incidents per Year
npdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Northern",]),
                  nrow(year_2019[year_2019$`Police District` == "Northern",]),
                  nrow(year_2020[year_2020$`Police District` == "Northern",]),
                  nrow(year_2021[year_2021$`Police District` == "Northern",]),
                  nrow(year_2022[year_2022$`Police District` == "Northern",]),
                  nrow(year_2023[year_2023$`Police District` == "Northern",]))
# Create data frame of vectors
npdDF <- data.frame(dataYears, npdIncidents)
# Create linear model and extrapolate
ggplot(npdDF, aes(x=dataYears, y=npdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Northern Police District")
```
```{r}
# Southern PD Forecast for number of crimes going forward

# Number of Incidents per Year
spdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Southern",]),
                  nrow(year_2019[year_2019$`Police District` == "Southern",]),
                  nrow(year_2020[year_2020$`Police District` == "Southern",]),
                  nrow(year_2021[year_2021$`Police District` == "Southern",]),
                  nrow(year_2022[year_2022$`Police District` == "Southern",]),
                  nrow(year_2023[year_2023$`Police District` == "Southern",]))
# Create data frame of vectors
spdDF <- data.frame(dataYears, spdIncidents)
# Create linear model and extrapolate
ggplot(spdDF, aes(x=dataYears, y=spdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T)+
  xlim(2018, 2025) + ggtitle("Southern Police District")
```
```{r}
# Bayview PD Forecast for number of crimes going forward

# Number of Incidents per Year
bpdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Bayview",]),
                  nrow(year_2019[year_2019$`Police District` == "Bayview",]),
                  nrow(year_2020[year_2020$`Police District` == "Bayview",]),
                  nrow(year_2021[year_2021$`Police District` == "Bayview",]),
                  nrow(year_2022[year_2022$`Police District` == "Bayview",]),
                  nrow(year_2023[year_2023$`Police District` == "Bayview",]))
# Create data frame of vectors
bpdDF <- data.frame(dataYears, bpdIncidents)
# Create linear model and extrapolate
ggplot(bpdDF, aes(x=dataYears, y=bpdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + xlim(2018, 2025) + ggtitle("Bayview Police District")
```
```{r}
# Ingleside PD Forecast for number of crimes going forward

# Number of Incidents per Year
ipdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Ingleside",]),
                  nrow(year_2019[year_2019$`Police District` == "Ingleside",]),
                  nrow(year_2020[year_2020$`Police District` == "Ingleside",]),
                  nrow(year_2021[year_2021$`Police District` == "Ingleside",]),
                  nrow(year_2022[year_2022$`Police District` == "Ingleside",]),
                  nrow(year_2023[year_2023$`Police District` == "Ingleside",]))
# Create data frame of vectors
ipdDF <- data.frame(dataYears, ipdIncidents)
# Create linear model and extrapolate
ggplot(ipdDF, aes(x=dataYears, y=ipdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Ingleside Police District")
```
```{r}
# Park PD Forecast for number of crimes going forward

# Number of Incidents per Year
ppdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Park",]),
                  nrow(year_2019[year_2019$`Police District` == "Park",]),
                  nrow(year_2020[year_2020$`Police District` == "Park",]),
                  nrow(year_2021[year_2021$`Police District` == "Park",]),
                  nrow(year_2022[year_2022$`Police District` == "Park",]),
                  nrow(year_2023[year_2023$`Police District` == "Park",]))
# Create data frame of vectors
ppdDF <- data.frame(dataYears, ppdIncidents)
# Create linear model and extrapolate
ggplot(ppdDF, aes(x=dataYears, y=ppdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) +
  xlim(2018, 2025) + ggtitle("Park Police District")
```
```{r}
# Richmond PD Forecast for number of crimes going forward

# Number of Incidents per Year
rpdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Richmond",]),
                  nrow(year_2019[year_2019$`Police District` == "Richmond",]),
                  nrow(year_2020[year_2020$`Police District` == "Richmond",]),
                  nrow(year_2021[year_2021$`Police District` == "Richmond",]),
                  nrow(year_2022[year_2022$`Police District` == "Richmond",]),
                  nrow(year_2023[year_2023$`Police District` == "Richmond",]))
# Create data frame of vectors
rpdDF <- data.frame(dataYears, rpdIncidents)
# Create linear model and extrapolate
ggplot(rpdDF, aes(x=dataYears, y=rpdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Richmond Police District")
```
```{r}
# Taraval PD Forecast for number of crimes going forward

# Number of Incidents per Year
tarapdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Taraval",]),
                  nrow(year_2019[year_2019$`Police District` == "Taraval",]),
                  nrow(year_2020[year_2020$`Police District` == "Taraval",]),
                  nrow(year_2021[year_2021$`Police District` == "Taraval",]),
                  nrow(year_2022[year_2022$`Police District` == "Taraval",]),
                  nrow(year_2023[year_2023$`Police District` == "Taraval",]))
# Create data frame of vectors
tarapdDF <- data.frame(dataYears, tarapdIncidents)
# Create linear model and extrapolate
ggplot(tarapdDF, aes(x=dataYears, y=tarapdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) +
  xlim(2018, 2025) + ggtitle("Taraval Police District")
```
```{r}
# Tenderloin PD Forecast for number of crimes going forward

# Number of Incidents per Year
tendpdIncidents <- c(nrow(year_2018[year_2018$`Police District` == "Tenderloin",]),
                  nrow(year_2019[year_2019$`Police District` == "Tenderloin",]),
                  nrow(year_2020[year_2020$`Police District` == "Tenderloin",]),
                  nrow(year_2021[year_2021$`Police District` == "Tenderloin",]),
                  nrow(year_2022[year_2022$`Police District` == "Tenderloin",]),
                  nrow(year_2023[year_2023$`Police District` == "Tenderloin",]))
# Create data frame of vectors
tendpdDF <- data.frame(dataYears, tendpdIncidents)
# Create linear model and extrapolate
ggplot(tendpdDF, aes(x=dataYears, y=tendpdIncidents)) + geom_point() + geom_smooth(method="lm", fullrange=T) + 
  xlim(2018, 2025) + ggtitle("Tenderloin Police District")
```
```{r}
# Looking at the unique Police districts in SF.
police_districs <- unique(incidentFrame$`Police District`)
police_districs
```
```{r}
# Summing up the crime count for each district
crime_count <- incidentFrame %>% group_by(`Police District`) %>% 
  summarise(count = n())
crime_count <- crime_count %>% arrange(count)
crime_count

crime_count <- crime_count %>%
  mutate(`Police District` = fct_reorder(`Police District`, count))
crime_count
```

```{r}
# Plotting the crime count to get a better picture
ggplot(crime_count, aes(x=`Police District`, y=count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Crimes", title = "Crime Count by District")

# This plot presents the overall crime per Police district in San Francisco. 
```
```{r}
# Looking at violent crimes and see what districts they take place in 
violent_crime <- unique(incidentFrame$`Incident Category`)
violent_crime
view(violent_crime)
```
```{r}
# Creating a DF with only Violent crimes.
violent_DF <- incidentFrame %>% filter(`Incident Category` %in% c("Assault", "Homicide", "Human Trafficking (A), Commercial Sex Acts", "Human Trafficking (B), Involuntary Servitude", "Human Trafficking, Commercial Sex Acts", "Rape", "Robbery","Suicide"))

violent_incident_counts <- violent_DF %>% 
  group_by(`Police District`) %>% 
  summarise(Count = n())

```
```{r}
#Creating a bar chart off of violent crimes
violent_incident_counts <- violent_incident_counts %>%
  mutate(`Police District` = fct_reorder(`Police District`, Count))

ggplot(violent_incident_counts, aes(x=`Police District`, y=Count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Crimes", title = "Crime Count by District")
```

```{r}
# Plot for all crime data and plot for violent crime data

#All Crime data
ggplot(crime_count, aes(x=`Police District`, y=count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Crimes", title = "Crime Count by District")


#Violent Crime Data
ggplot(violent_incident_counts, aes(x=`Police District`, y=Count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Crimes", title = "Violent Crime Count by District")
```

```{r}
# I want the bar charts to match on the x label. Below is the code for that.
district_order <- crime_count$`Police District`

violent_incident_counts <- violent_incident_counts %>% 
  mutate(`Police District` = factor(`Police District`, levels = district_order))

#All Crime data
ggplot(crime_count, aes(x=`Police District`, y=count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Crimes", title = "Crime Count by District")

#Violent Crime Data
ggplot(violent_incident_counts, aes(x=`Police District`, y=Count)) + 
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(x = "Police District", y = "Number of Violent Crimes", title = "Violent Crime Count by District")

# The bar charts now follow the Police Districts with the most overall crime. You can see that Violent crimes do not follow the same order once you get to the higher crime rate areas. 'Tenderloin' and 'Mission' Districts stand out the most.
```


































